import React, { useState } from "react"
import type { FieldData } from "@/types"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import AvatarUpload from "@/components/file-upload/avatar-upload"
import TableUpload from "@/components/file-upload/table-upload"
import { ComboboxField } from "@/components/fields/ComboboxField"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "./ui/select"

// If textarea doesn't exist, I'll stick to Input or standard textarea
// Check Shadcn Input.

interface ResourceFormProps {
    fields: FieldData[]
    initialData?: Record<string, any>
    onSubmit: (data: Record<string, any>) => Promise<void>
    onCancel?: () => void
    submitLabel?: string
    hideCancel?: boolean
    container?: HTMLElement | null
}

export function ResourceForm({
    fields,
    initialData = {},
    onSubmit,
    onCancel,
    submitLabel = "Save",
    hideCancel = false,
    container,
}: ResourceFormProps) {
    const [formData, setFormData] = useState<Record<string, any>>(initialData)
    const [loading, setLoading] = useState(false)
    const [_, setErrors] = useState<Record<string, string>>({})

    React.useEffect(() => {
        setFormData(initialData)
    }, [JSON.stringify(initialData)])



    const handleChange = (key: string, value: any) => {
        setFormData((prev) => ({ ...prev, [key]: value }))
    }

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        setLoading(true)
        setErrors({})
        try {
            await onSubmit(formData)
        } catch (error: any) {
            console.error(error)
            // Handle validation errors from backend if standard format
        } finally {
            setLoading(false)
        }
    }

    return (
        <form onSubmit={handleSubmit} className="space-y-4 pt-4">
            {fields.map((field) => {
                if (field.read_only) return null // Skip read-only fields in form? Or show as disabled? 
                // User might want to see ID details in Update.
                // Usually ReadOnly fields are shown but disabled.

                // For Create, maybe skip ID? ID usually generated by backend.
                // If it's "create_fields", the backend likely filtered out auto-increment IDs if configured 'HideOnCreate'.

                return (
                    <div key={field.key} className="space-y-2">
                        <Label htmlFor={field.key}>
                            {field.name || field.label}
                            {field.required && <span className="text-red-500 ml-1">*</span>}
                        </Label>
                        {/* Simple switch for types */}
                        {renderInput(field, formData[field.key] || "", (val) => handleChange(field.key, val), container)}
                        {field.help_text && (
                            <p className="text-xs text-muted-foreground">{field.help_text}</p>
                        )}
                    </div>
                )
            })}

            <div className="flex flex-col-reverse md:flex-row md:justify-end gap-3 pt-6">
                {!hideCancel && (
                    <Button type="button" variant="outline" onClick={onCancel} disabled={loading} className="w-full md:w-auto h-12 md:h-10 text-base">
                        Cancel
                    </Button>
                )}
                <Button type="submit" disabled={loading} className="w-full md:w-auto h-12 md:h-10 text-base">
                    {loading ? "Saving..." : submitLabel}
                </Button>
            </div>
        </form>
    )
}

function renderInput(
    field: FieldData,
    value: any,
    onChange: (val: any) => void,
    container?: HTMLElement | null
) {
    // Normalize object values (relationships) to ID or empty string to prevent React errors
    let normalizedValue = value;
    if (typeof value === 'object' && value !== null) {
        // Check for empty/zero object
        const id = value.id || value.ID;
        if (id && id !== 0) {
            normalizedValue = id;
        } else {
            normalizedValue = "";
        }
    }

    const commonProps = {
        id: field.key,
        name: field.key,
        disabled: field.disabled || field.read_only,
        placeholder: field.placeholder,
        required: field.required,
        value: normalizedValue,
        onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(e.target.value),
    }

    // You can expand this based on field.view or field.type (which is not in interface but view is)
    // view: "text-field", "password-field", "email-field", etc.


    // Use type if available for specific input types
    // Custom Upload Components
    if (field.view === "image-field") {
        return (
            <AvatarUpload
                className="w-full"
                defaultAvatar={typeof value === 'string' ? value : undefined}
                onFileChange={(file) => {
                    onChange(file ? file.file : null)
                }}
            />
        )
    }

    if (field.type === "file" || field.view === "file-field") {
        return (
            <TableUpload
                maxFiles={field.props?.multiple ? 10 : 1}
                multiple={field.props?.multiple}
                simulateUpload={false} // Real upload handled by form submit
                // TableUpload expects FileWithPreview[], form state holds File objects or strings (urls)
                // We need to handle this impedance mismatch if we want to show existing files.
                // For now, onFilesChange updates the form state with selected files.
                onFilesChange={(files) => {
                    // If multiple, pass array of Files. If single, pass first File.
                    if (field.props?.multiple) {
                        onChange(files.map(f => f.file))
                    } else {
                        onChange(files.length > 0 ? files[0].file : null)
                    }
                }}
            />
        )
    }

    switch (field.view) {
        case "password-field":
            return <Input type="password" {...commonProps} />
        case "email-field":
            return <Input type="email" {...commonProps} />
        case "number-field":
            return <Input type="number" {...commonProps} />
        case "date-field":
            return <Input type="date" {...commonProps} />
        case "textarea-field":
            return <Textarea {...commonProps} />
        case "switch-field":
        case "boolean-field":
            return (
                <div className="flex items-center space-x-2">
                    <Switch
                        id={field.key}
                        checked={!!value}
                        disabled={field.disabled || field.read_only}
                        onCheckedChange={(checked) => onChange(checked)}
                    />
                </div>
            )
        case "has-one-field":
        case "belongs-to-field":
        case "combobox-field":
            // eslint-disable-next-line no-case-declarations
            const options = (field.props?.options as Record<string, string>) || {}
            // eslint-disable-next-line no-case-declarations
            const items = Object.entries(options).map(([val, label]) => ({
                value: val,
                label: label,
            }))

            // Find selected label for display if needed, but Combobox should handle it if value matches
            // Ensure value is string to match options keys
            const stringValue = value !== null && value !== undefined ? String(value) : ""

            return (
                <ComboboxField
                    value={stringValue}
                    options={items}
                    onChange={(val) => onChange(val)}
                    placeholder={field.placeholder || "Select option..."}
                    container={container}
                />
            )
        case "belongs-to-many-field":
            // eslint-disable-next-line no-case-declarations
            const btmOptions = (field.props?.options as Record<string, string>) || {}
            // eslint-disable-next-line no-case-declarations
            const btmItems = Object.entries(btmOptions).map(([val, label]) => ({
                value: val,
                label: label,
            }))

            // Ensure value is array of strings
            // eslint-disable-next-line no-case-declarations
            let btmValue: string[] = []
            if (Array.isArray(value)) {
                btmValue = value.map(v => {
                    if (typeof v === 'object' && v !== null) {
                        return String(v.id || v.ID || '')
                    }
                    return String(v)
                }).filter(v => v !== '')
            } else if (value) {
                if (typeof value === 'object' && value !== null) {
                     const id = (value as any).id || (value as any).ID
                     if (id) btmValue = [String(id)]
                } else {
                    btmValue = [String(value)]
                }
            }

            return (
                <ComboboxField
                    value={btmValue}
                    options={btmItems}
                    onChange={(val) => onChange(val)}
                    placeholder={field.placeholder || "Select items..."}
                    multiple={true}
                    container={container}
                />
            )
        case "select-field":

            // eslint-disable-next-line no-case-declarations
            const _options = (field.props?.options as Record<string, string>) || {}
            // eslint-disable-next-line no-case-declarations
            const _items = Object.entries(_options).map(([val, label]) => ({
                value: val,
                label: label,
            }))

            return (
                <Select
                    defaultValue={String(value).toLowerCase()}
                    value={String(value).toLowerCase()}
                    onValueChange={(val) => onChange(val)}
                >

                    <SelectTrigger className="w-full">
                        <SelectValue placeholder={field.placeholder || "Select option..."} />
                    </SelectTrigger>
                    <SelectContent container={container}>
                        <SelectGroup>
                            {_items.map((item) => (
                                <SelectItem key={item.value} value={item.value}>
                                    {item.label}
                                </SelectItem>
                            ))}
                        </SelectGroup>
                    </SelectContent>
                </Select>
            )
        default:
            return <Input type="text" {...commonProps} />
    }
}
